[workspace]
resolver = "2"
members = [
    "crates/gdal-alt-core",
    "fastcog",
    "fastinfo",
    "fastvalidate",
    "fastcrop",
    "fastband",
    "fastfootprint",
    "fasttranslate",
]
exclude = ["python/gdal-alt-py"]

[workspace.package]
edition = "2021"
license = "MIT"

[patch.crates-io]
geotiff-writer = { path = "fastcog/vendor/geotiff-writer" }

[profile.release]
lto = true
codegen-units = 1

[profile.release.package."*"]
opt-level = 3
