[package]
name = "gdal-alt-py"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Python bindings for gdal-alt-core (PyO3)"

[workspace]

[lib]
name = "gdal_alt"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
gdal-alt-core = { path = "../../crates/gdal-alt-core" }
pyo3 = { version = "0.23", features = ["extension-module"] }

[patch.crates-io]
geotiff-writer = { path = "../../fastcog/vendor/geotiff-writer" }
